# Generated by Django 5.1.6 on 2025-04-30 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0002_alter_artikel_options_alter_kategori_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artikel",
            old_name="Kategori",
            new_name="kategori",
        ),
    ]
