# Generated by Django 5.2.1 on 2025-05-07 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0003_rename_kategori_artikel_kategori"),
    ]

    operations = [
        migrations.AddField(
            model_name="artikel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artikel",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
